import java.util.HashMap;

public class ConsolePrinter {
    public static void printBoard(ChessBoard board){ //TODO clean up raw use
        HashMap<Position, ChessSpace> chessboard = board.getChessBoardHash();
        System.out.println("  a b c d e f g h");
        String line = "";
        line += "8 ";
        line += chessboard.get(Positions.a8).toString();
        line += chessboard.get(Positions.b8).toString();
        line += chessboard.get(Positions.b8).toString();
        line += chessboard.get(Positions.c8).toString();
        line += chessboard.get(Positions.d8).toString();
        line += chessboard.get(Positions.e8).toString();
        line += chessboard.get(Positions.f8).toString();
        line += chessboard.get(Positions.g8).toString();
        line += chessboard.get(Positions.h8).toString();
        System.out.println(line);
        line = "";
        line += "7 ";
        line += chessboard.get(Positions.a7).toString();
        line += chessboard.get(Positions.b7).toString();
        line += chessboard.get(Positions.c7).toString();
        line += chessboard.get(Positions.d7).toString();
        line += chessboard.get(Positions.e7).toString();
        line += chessboard.get(Positions.f7).toString();
        line += chessboard.get(Positions.g7).toString();
        line += chessboard.get(Positions.h7).toString();
        System.out.println(line);
        line = "";
        line += "6 ";
        line += chessboard.get(Positions.a6).toString();
        line += chessboard.get(Positions.b6).toString();
        line += chessboard.get(Positions.c6).toString();
        line += chessboard.get(Positions.d6).toString();
        line += chessboard.get(Positions.e6).toString();
        line += chessboard.get(Positions.f6).toString();
        line += chessboard.get(Positions.g6).toString();
        line += chessboard.get(Positions.h6).toString();
        System.out.println(line);
        line = "";
        line += "5 ";
        line += chessboard.get(Positions.a5).toString();
        line += chessboard.get(Positions.b5).toString();
        line += chessboard.get(Positions.c5).toString();
        line += chessboard.get(Positions.d5).toString();
        line += chessboard.get(Positions.e5).toString();
        line += chessboard.get(Positions.f5).toString();
        line += chessboard.get(Positions.g5).toString();
        line += chessboard.get(Positions.h5).toString();
        System.out.println(line);
        line = "";
        line += "4 ";
        line += chessboard.get(Positions.a4).toString();
        line += chessboard.get(Positions.b4).toString();
        line += chessboard.get(Positions.c4).toString();
        line += chessboard.get(Positions.d4).toString();
        line += chessboard.get(Positions.e4).toString();
        line += chessboard.get(Positions.f4).toString();
        line += chessboard.get(Positions.g4).toString();
        line += chessboard.get(Positions.h4).toString();
        System.out.println(line);
        line = "";
        line += "3 ";
        line += chessboard.get(Positions.a3).toString();
        line += chessboard.get(Positions.b3).toString();
        line += chessboard.get(Positions.c3).toString();
        line += chessboard.get(Positions.d3).toString();
        line += chessboard.get(Positions.e3).toString();
        line += chessboard.get(Positions.f3).toString();
        line += chessboard.get(Positions.g3).toString();
        line += chessboard.get(Positions.h3).toString();
        System.out.println(line);
        line = "";
        line += "2 ";
        line += chessboard.get(Positions.a2).toString();
        line += chessboard.get(Positions.b2).toString();
        line += chessboard.get(Positions.c2).toString();
        line += chessboard.get(Positions.d2).toString();
        line += chessboard.get(Positions.e2).toString();
        line += chessboard.get(Positions.f2).toString();
        line += chessboard.get(Positions.g2).toString();
        line += chessboard.get(Positions.h2).toString();
        System.out.println(line);
        line = "";
        line += "1 ";
        line += chessboard.get(Positions.a1).toString();
        line += chessboard.get(Positions.b1).toString();
        line += chessboard.get(Positions.c1).toString();
        line += chessboard.get(Positions.d1).toString();
        line += chessboard.get(Positions.e1).toString();
        line += chessboard.get(Positions.f1).toString();
        line += chessboard.get(Positions.g1).toString();
        line += chessboard.get(Positions.h1).toString();
        System.out.println(line);
    }
}
